controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_1_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    joints:
      - _finger_joint1