version: '3.0'
services:
  ros_melodic_vnc_base:
    build: 
      context: ./melodic_vnc_base
      dockerfile: Dockerfile_base

  ros_melodic_vnc_techman:
    build:
      context: ./techman_vnc
      dockerfile: Dockerfile_tm
